### ISSUE TITLE
Not sure how to solve this Markbot issue

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/simple-to-do-list#1]
Hey @thomasjbradley

I need help solving what this Markbot issue means. The items that get added to the list toggle a class with line-through but it says it doesn't change.

Thanks for the help!
Jess

<img width="816" alt="Screen Shot 2020-03-21 at 1 18 39 PM" src="https://user-images.githubusercontent.com/43217543/77232355-e9bcd100-6b76-11ea-943a-c77e802e2df9.png">

**Comment by thomasjbradley** [comment]
It’s Markbot not you. Markbot’s CSS interpreter is reading more than just `line-through` in the  CSS—it’s getting all the new `text-decoration` properties too—meaning it doesn’t match what Markbot is expecting.

So, yours is perfect!
